### ISSUE TITLE
Error loading Services

### ISSUE THREAD

**Issue by alberto-leon-crespo** [zazoomauro/node-dependency-injection#82]
Hi i became a implementation in my own framework based on express. This is the folder structure:

```
|-- app
|   |-- app.ts
|   |-- config
|   |   |-- parameters.yaml
|   |   |-- routes.yaml
|   |   `-- services.yaml
|   |-- controllers
|   |   `-- users.controller.ts
|   |-- core
|   |   `-- controller.ts
|   |-- server.ts
|   `-- services
|       `-- dummy.service.ts
```

I load config file in my app.ts file with this function:

```
// app/app.ts
private loadDependencyInjection(){
   let container = new ContainerBuilder();
   let loader = new YamlFileLoader(container);
   loader.load('app/config/services.yaml');
   console.log(loader);
   container.compile();
   this.container = container;
}
```

This is my services.yaml file:
```yml
# app/config/services.yaml
services:
    dummy.service:
        class: './../services/dummy.service'
```
This is my dummy.service file:
```
class DummyService{
    public getName(){
        return 'DummyService';
    }
}

export default DummyService;
```
But when i try to load application i get this error:
```
Error: Cannot find module 'app/services/dummy.service'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at YamlFileLoader._requireClassNameFromPath (/home/mastercss/node/node_modules/node-dependency-injection/dist/lib/Loader/FileLoader.js:345:14)
    at YamlFileLoader._getDefinition (/home/mastercss/node/node_modules/node-dependency-injection/dist/lib/Loader/FileLoader.js:131:27)
    at YamlFileLoader._parseDefinition (/home/mastercss/node/node_modules/node-dependency-injection/dist/lib/Loader/FileLoader.js:90:47)
    at YamlFileLoader._parseDefinitions (/home/mastercss/node/node_modules/node-dependency-injection/dist/lib/Loader/FileLoader.js:69:16)
    at YamlFileLoader.load (/home/mastercss/node/node_modules/node-dependency-injection/dist/lib/Loader/YamlFileLoader.js:65:12)
    at App.loadDependencyInjection (/home/mastercss/node/app/app.ts:119:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs@1.0.0 dev: `ts-node ./app/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-18T00_41_54_260Z-debug.log
```

Do u have any idea of what is wrong?

**Comment by zazoomauro** [comment]
hi @alberto-leon-crespo ! I think typescript is not supported at the moment! DI tries to load javascripts files and not ts. Can you try to rename your filename to `.js` instead of `.ts`

**Comment by alberto-leon-crespo** [comment]
Hi @zazoomauro ! I rename filename to '.js' but i get the same error. I try to debug program but i cant dump the informatión of path in load process. I tried with console.log, utils.debug and something similar but i cant.

¿how i can debug module to add this funcionality?

**Comment by zazoomauro** [comment]
@alberto-leon-crespo may be can be a filename error issues. Can you try to remove the dots in the filename? like: instead of `dummy.service.js` to `dummyService.js`
if fails there is bug with dots in the filename

**Comment by alberto-leon-crespo** [comment]
@zazoomauro removing dot in the filename i get the same error. I try to debug module

**Comment by zazoomauro** [comment]
@alberto-leon-crespo let me know

**Comment by alberto-leon-crespo** [comment]
@zazoomauro I solve the problem with the next fix in the file Loader.js in method `_requireClassNameFromPath`.

```javascript
return require(process.cwd() + "/" + path.join(fromDirectory, classObject)).default;
```

Can u fix that?

**Comment by zazoomauro** [comment]
@alberto-leon-crespo I stil not convinced. process.cwd() contains exactly the same value of from directory.
Can you please show me the output of your `fromDirectory` parameter? 
Can you please show me the output of your `this.filePath` parameter?

**Comment by alberto-leon-crespo** [comment]
@zazoomauro I think load of classes has been relative to project directory, but is only a opinion. Here values of `fromDirectory` and `this.filePath`:

fromDirectory: app/config
this.filePath: app/config/services.yaml

**Comment by zazoomauro** [comment]
@alberto-leon-crespo
I know what is going on.
Can u please send the ABSOLUTE path during your configuration file loader?
So instead of this
`loader.load('app/config/services.yaml');`
use semthing like this:
`loader.load(path.join(__dirname, 'app/config/services.yaml'));`

**Comment by zazoomauro** [comment]
Then we can discuss if only enabling absolute path during loading is good or bad.
We can enable a flag to enable relative file path loading... etc..

**Comment by alberto-leon-crespo** [comment]
I think is good idea. I try to load config file with `loader.load(path.join(__dirname, 'app/config/services.yaml'));`. BTW i can fix the problem until you publish enchancement.

**Comment by zazoomauro** [comment]
@alberto-leon-crespo should be ready for the 2.1 version.

**Comment by alberto-leon-crespo** [comment]
I only can fix the problem using process.cwd() function to get absolute path based on project folder.
